version: 0.22.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release

shallow_clone: true

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  GOOGLE_API_KEY:
    secure: pnYRPfFKB+uub3hlM9mX2q3CzVKsqCg/EM/lFZ2DN6yePU4wBbhr0PhBf3dDVgU4

init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - msbuild src\GoogleMapsForNET.sln /t:restore

build_script:
- cmd: msbuild src\GoogleMapsForNET.sln /t:build /p:Configuration=Release /verbosity:minimal

before_test:
- cmd: curl -isS "https://maps.googleapis.com/maps/api/geocode/json?address=1600+Pennsylvania+Ave+NW%2c+Washington%2c+DC+20500%2c+USA&key=%GOOGLE_API_KEY%" 

after_test:
- cmd: nuget pack gmaps-api-net.nuspec -version %APPVEYOR_BUILD_VERSION%

artifacts:
- path: '*.nupkg'
  name: NuGetPackage

deploy:
- provider: NuGet
  api_key:
    secure: 2SwDMmXZZtgoLWsldKZ8GCu9rZXpO5quTYtSNJQSeeiqDjnmo0OfutNVcH3jsfpj
  artifact: 'NuGetPackage'
  on:
    branch: release

notifications:
- provider: Email
  to:
  - ericnewton76@gmail.com
  subject: Gmaps-api-net build completed.
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

# Temporary workaround for AppVeyor -> NuGet connectivity issues
hosts:
  api.nuget.org: 93.184.221.200